apiVersion: v1
kind: Pod
metadata:
  name: db-restaurante
  namespace: fiap
  labels:
    app: db-restaurante
spec:
  containers:
    - name: db-restaurante-container
      image: "postgres:14"
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-configmap-restaurante
        - secretRef:
            name: db-secret
