name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      - name: Update Kubernetes config
        run:  aws eks update-kubeconfig --region us-east-2 --name staging-demo

      - name: Check get Nodes
        run: kubectl get nodes

      - name: Get privileges
        run: kubectl auth can-i "*" "*"

      - name: Show kubernetes configs
        run:  kubectl config view --minify 

      - name: Apply Kubernetes changes
        run: kubectl apply -f ../kubernetes

      - name: Show kubernetes service loadbalancer
        run: kubectl get svc -n fiap
